services:
  redis:
    container_name: redis
    restart: always
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: todoapp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY='django-insecure-)!w7$7wxdo*5@db%t#s2914wn(-ucf!)945v%p+$uobt@_k_%j'
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BEAT_SCHEDULER=django_celery_beat.schedulers.DatabaseScheduler
  celery_worker:
    build: .
    image: celery_worker
    command: celery -A core worker -l INFO
    depends_on:
      - redis
      - backend
    volumes:
      - ./core:/app
    environment:
      - SECRET_KEY='django-insecure-)!w7$7wxdo*5@db%t#s2914wn(-ucf!)945v%p+$uobt@_k_%j'
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BEAT_SCHEDULER=django_celery_beat.schedulers.DatabaseScheduler
  celery_beat:
    build: .
    image: celery_beat
    command: celery -A core beat -l info
    volumes:
      - ./core:/app
    environment:
      - SECRET_KEY='django-insecure-)!w7$7wxdo*5@db%t#s2914wn(-ucf!)945v%p+$uobt@_k_%j'
      - DEBUG=True
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BEAT_SCHEDULER=django_celery_beat.schedulers.DatabaseScheduler
    depends_on:
      - redis